{{- if and .Values.ingress.enabled (eq .Values.ingress.class "traefik") (not .Values.global.kong.enabled) }}
{{- $trusted := pluck "certificates" .Values.global.trusted .Values.trusted | compact | first | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: trusted-certificates-traefik
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
type: Opaque
data:
  tls.ca: {{ required "List of trusted certificates is required: .Values.trusted.certificates!" $trusted }}
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: {{ include "czertainly.fullname" . }}-mtls
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
spec:
  clientAuth:
    secretNames:
      - trusted-certificates-traefik
    clientAuthType: RequireAndVerifyClientCert
{{- end }}
