{{- $redisPort := .Values.service.port }}
{{- $additionalPorts := (include "caching-redis.customization.ports" $) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caching-redis.fullname" . }}
  labels:
    {{- include "caching-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ $redisPort }}
      targetPort: redis
      protocol: "TCP"
    {{- if $additionalPorts }}
      {{- $additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "caching-redis.selectorLabels" . | nindent 4 }}
