apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy.fullname" . }}-secret
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.amqp.password }}
  amqpPassword: {{ .Values.amqp.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.amqp.entraId.clientSecret }}
  entraIdClientSecret: {{ .Values.amqp.entraId.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.token }}
  configToken: {{ .Values.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.tokenSigningKey }}
  tokenSigningKey: {{ .Values.tokenSigningKey | b64enc | quote }}
  {{- end }}
