apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy.fullname" . }}-secret
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.amqp.key }}
  amqpKey: {{ .Values.amqp.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.amqp.entraId.clientSecret }}
  entraIdClientSecret: {{ .Values.amqp.entraId.clientSecret | b64enc | quote }}
  {{- end }}
