annotations:
  category: trustLifecycleManagement
apiVersion: v2
appVersion: "1.0.0"
name: proxy
description: A Helm chart for Azure Service Bus / RabbitMQ proxy
home: https://github.com/3KeyCompany/CZERTAINLY
icon: https://github.com/3KeyCompany/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg
keywords:
  - czertainly
  - proxy
  - amqp
  - azure-service-bus
  - rabbitmq
  - messaging
maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/3KeyCompany/CZERTAINLY-Helm-Charts
type: application
sources:
  - https://github.com/3KeyCompany/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com
version: 1.0.1

dependencies:
  - name: czertainly-lib
    repository: file://../czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    version: 1.4.2
