{{- $scripts := or .Values.global.keycloak.enabled .Values.registerAdmin.enabled .Values.global.entraId.enabled }}
{{- if $scripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-scripts-configmap
data:
  {{- if .Values.registerAdmin.enabled }}
  register-admin.sh: |
    {{- tpl (.Files.Get "scripts/register-admin.sh") . | indent 4 }}
  {{- end }}
  {{- if .Values.global.keycloak.enabled }}
  register-internal-keycloak.sh: |
    {{- tpl (.Files.Get "scripts/register-internal-keycloak.sh") . | indent 4 }}
  {{- end }}
  {{- if .Values.global.entraId.enabled }}
  register-entraid-oidc.sh: |
    {{- tpl (.Files.Get "scripts/register-entraid-oidc.sh") . | indent 4 }}
  {{- end }}
{{- end }}
