apiVersion: v1
kind: Secret
metadata:
  name: messaging-secret
stringData:
  {{- $externalMessaging := pluck "enabled" .Values.global.messaging.external .Values.messaging.external | compact | first }}
  {{- if $externalMessaging }}
  messaging.username: {{ pluck "username" .Values.global.messaging .Values.messaging | compact | first | quote }}
  messaging.password: {{ pluck "password" .Values.global.messaging .Values.messaging | compact | first | quote }}
  messaging.core.username: {{ pluck "coreUsername" .Values.global.messaging .Values.messaging | compact | first | quote }}
  messaging.core.password: {{ pluck "corePassword" .Values.global.messaging .Values.messaging | compact | first | quote }}
  messaging.provisioner.username: {{ pluck "provisionerUsername" .Values.global.messaging .Values.messaging | compact | first | quote }}
  messaging.provisioner.password: {{ pluck "provisionerPassword" .Values.global.messaging .Values.messaging | compact | first | quote }}
  messaging.proxy.username: {{ pluck "proxyUsername" .Values.global.messaging .Values.messaging | compact | first | quote }}
  messaging.proxy.password: {{ pluck "proxyPassword" .Values.global.messaging .Values.messaging | compact | first | quote }}
  {{- else }}
  messaging.username: {{ pluck "username" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.password: {{ pluck "password" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.core.username: {{ pluck "coreUsername" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.core.password: {{ pluck "corePassword" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.provisioner.username: {{ pluck "provisionerUsername" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.provisioner.password: {{ pluck "provisionerPassword" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.proxy.username: {{ pluck "proxyUsername" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.proxy.password: {{ pluck "proxyPassword" .Values.global.messaging .Values.messagingService.messaging | compact | first | quote }}
  messaging.cookie: {{ .Values.messagingService.messaging.erlang.cookie | quote }}
  messaging.definitions.json: |-
    {{- include "messaging-rabbitmq.definitions.json" (dict "global" .Values.global "messagingService" .Values.messagingService) | indent 4 }}
  {{- end }}
