apiVersion: v2
type: application
name: caching-redis
version: 7.4.2-1-develop
appVersion: 7.4.2

annotations:
  category: trustLifecycleManagement

description: A Helm chart for CZERTAINLY platform Redis caching service.
home: https://github.com/CZERTAINLY/CZERTAINLY-Helm-Charts
icon: https://github.com/CZERTAINLY/CZERTAINLY/blob/master/czertainly-logo/czertainly_sign_color.svg

keywords:
  - czertainly
  - redis
  - caching
  - session

maintainers:
  - name: CZERTAINLY
    email: info@czertainly.com
    url: https://github.com/CZERTAINLY/CZERTAINLY-Helm-Charts

sources:
  - https://github.com/CZERTAINLY/CZERTAINLY
  - https://www.czertainly.com
  - https://docs.czertainly.com

dependencies:
  - name: czertainly-lib
    repository: file://../czertainly-lib
    # repository: oci://harbor.3key.company/czertainly-helm
    version: 1.4.2
